version: "3"

services:
  app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/src/app
    links:
      - db
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    env_file:
      - ./notifications_api/.env

    depends_on:
        - db
  db:
      image: postgres:13-alpine
      env_file:
         - ./notifications_api/.env
      ports:
          - "5433:5432"
      volumes:
          - postgres-volume:/var/lib/postgresql/data/
  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A notifications_api worker --beat -l INFO
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./notifications_api/.env
    depends_on:
      - app
      - db
      - redis


volumes:
  postgres-volume: